# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - mdst-submission

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read #This is required for actions/checkout

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python version
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            # - name: Create and start virtual environment
            #   run: |
            #       python -m venv client/venv
            #       source client/venv/bin/activate

            # - name: Install dependencies
            #   run: pip install -r client/requirements.txt

            # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

            - name: Zip artifact for deployment (Deploying client)
              run: zip -r release.zip client/

            - name: Upload artifact for deployment jobs
              uses: actions/upload-artifact@v4
              with:
                  name: python-app
                  path: |
                      release.zip
                      !client/venv/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT
            contents: read #This is required for actions/checkout

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: python-app

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5EF9A9B10A9143328CC579EAB11C21E9 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9BEE8F081A41443495F61EDE8779E2FD }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D33F86EB456243439F71375A422F59D2 }}

            - name: "Deploy to Azure Web App"
              uses: azure/webapps-deploy@v3
              id: deploy-to-webapp
              with:
                  app-name: "mdst-submission"
                  slot-name: "Production"
